name: main
on: push

jobs:
  testing:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
          path: ./ve1

      - run: |
          python3 -m venv ve1
          pip install requests

  check:
    name: test
    runs-on: ubuntu-22.04
    needs: [testing]
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - name: Attempt to restore cached virtualenv
        uses: actions/cache@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
          path: ./ve1

      - run: |
          python3 -m venv ve1
          pip install requests
