name: main
on: push

jobs:
  testing:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - run: |
          python3 -m venv ve1
          pip install requests

      - name: Cache virtualenv on cache-miss
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
          path: ./ve1

  check:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - name: Attempt to restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}
          path: ./ve1

      - run: |
          python3 -m venv ve1
          pip install requests
