name: main
on: push

jobs:
  testing:
    name: Test job
    runs-on: ubuntu-22.04
    steps:

      - run: |
          echo $PATH

      - run: |
          wget --quiet https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -zxvf openshift-client-linux.tar.gz oc -C /usr/local/bin/
          # mv -v oc /usr/local/bin/
          # echo "$PWD/oc" >> $GITHUB_PATH
          rm -f openshift-client-linux.tar.gz
          oc version --client

      - run: |
          oc version --client