name: main
on: push

jobs:
  testing:
    name: Test job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - run: |
          pip install requests


  check:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.10'

      - run: |
          pip install requests
