name: main
on: push

jobs:
  testing:
    name: Test job
    runs-on: ubuntu-22.04
    steps:

      - run: |
          wget --progress=bar:force:noscroll https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz